/**
 * Book 6 — 30 Rules for the Master Swing Trader (Alan Farley)
 *
 * 20 questions covering all 30 rules of swing trading.
 * Short, dense book — each rule is a paragraph with a key insight.
 */

import type { QuizQuestion } from "./types";

export const BOOK_06_META = {
  id: 6,
  title: "30 Rules for the Master Swing Trader",
  shortTitle: "30 Rules — Swing Trader",
};

export const BOOK_06_QUESTIONS: QuizQuestion[] = [
  {
    id: 1,
    bookId: 6,
    chapter: null,
    topic: "Rule #1",
    question: "Rule #1: 'If you have to look, it isn't there.' What does this mean for swing traders?",
    options: [
      "Always use glasses when looking at charts",
      "The best trades jump out at you and create urgency — if you have to search for a setup, it probably isn't a good one",
      "Never look at your P&L during a trade",
      "Don't use technical indicators",
    ],
    answer: 1,
    explanation: "Trust your instincts. The best setups are obvious and create a sense of urgency. If you have to convince yourself a trade is there, act quickly or move on.",
  },
  {
    id: 2,
    bookId: 6,
    chapter: null,
    topic: "Rule #3",
    question: "Rule #3: 'Price has memory.' What does the author mean?",
    options: [
      "Stock prices never change",
      "When price returns to a level where it previously reversed, the same battle between buyers and sellers tends to repeat",
      "You should memorize every stock price",
      "Prices always go up over time",
    ],
    answer: 1,
    explanation: "Prior price action at a level predicts future behavior there. When price returns to a past battleground, watch the tape — history tends to rhyme.",
  },
  {
    id: 3,
    bookId: 6,
    chapter: null,
    topic: "Rule #4",
    question: "Rule #4: 'Profit and discomfort stand side by side.' What is the trading lesson?",
    options: [
      "Profitable trades always feel comfortable",
      "The setup that scares you most is often the one you need to take — if it felt good, everyone would trade it",
      "Never trade if you feel uncomfortable",
      "Profits come from trading only when you're relaxed",
    ],
    answer: 1,
    explanation: "Ancient wisdom: what first brings pleasure ends in pain, but what first causes pain ends in great pleasure. The best trades feel uncomfortable at entry.",
  },
  {
    id: 4,
    bookId: 6,
    chapter: null,
    topic: "Rule #5",
    question: "Rule #5: 'Stand apart from the crowd at all times.' How should a swing trader relate to the crowd?",
    options: [
      "Always follow what everyone else is doing",
      "Trade ahead, behind, or contrary to the crowd — your job is to take their money before they take yours",
      "Only trade stocks that are trending on social media",
      "Wait for consensus before entering any trade",
    ],
    answer: 1,
    explanation: "Be the first in and first out of the profit door. Your success depends on pouncing on ill-advised decisions, poor judgment, and bad timing of others.",
  },
  {
    id: 5,
    bookId: 6,
    chapter: null,
    topic: "Rule #6",
    question: "Rule #6: 'Buy the first pullback from a new high. Sell the first pullback from a new low.' Why?",
    options: [
      "Because pullbacks always lead to new highs",
      "Trends often test the last support/resistance before continuing — you're trading with the crowd that missed the initial move",
      "Because the second pullback is always bigger",
      "Because the first pullback is always exactly 50%",
    ],
    answer: 1,
    explanation: "After a breakout to new highs, the first pullback tests the breakout level. Buying this test puts you with the latecomers who missed the initial move and add fuel.",
  },
  {
    id: 6,
    bookId: 6,
    chapter: null,
    topic: "Rule #8",
    question: "Rule #8: 'Short rallies, not selloffs.' When should you enter a short position?",
    options: [
      "During the sharpest part of a decline",
      "Wait for a bounce/rally after the selloff — short sellers cover into declines, so enter after they're squeezed out and the rally fades",
      "At the exact bottom of the selloff",
      "Only on Fridays before the weekend",
    ],
    answer: 1,
    explanation: "Short-sellers cover into declines (the worst time to enter new shorts). Wait for them to get squeezed out on a rally, then jump on board while no one is watching.",
  },
  {
    id: 7,
    bookId: 6,
    chapter: null,
    topic: "Rule #10",
    question: "Rule #10: 'Avoid the open.' The author says 'They see you coming, sucker.' What does he mean?",
    options: [
      "Never trade stocks that had their IPO today",
      "The market open is dominated by emotional orders and professional manipulation — amateurs get exploited in the first minutes",
      "Open a different browser when trading",
      "Only trade during after-hours",
    ],
    answer: 1,
    explanation: "The open is where emotional overnight orders meet professional execution. The opening 15-30 minutes are the most manipulated — professionals feed on amateur urgency.",
  },
  {
    id: 8,
    bookId: 6,
    chapter: null,
    topic: "Rule #11",
    question: "Rule #11: 'Trades that work in hot markets destroy accounts in cool ones.' What percentage of the time do stocks actually trend?",
    options: [
      "50-60% of the time",
      "75-80% of the time",
      "Only 15-20% of the time",
      "100% of the time — stocks always trend",
    ],
    answer: 2,
    explanation: "Stocks only trend 15-20% of the time. The rest is trading ranges. Momentum strategies that crush it in hot markets will bleed you dry in sideways ones.",
  },
  {
    id: 9,
    bookId: 6,
    chapter: null,
    topic: "Rule #12",
    question: "Rule #12: 'The best trades show major convergence.' What is convergence?",
    options: [
      "When two stocks merge into one",
      "When multiple independent signals — price, time, indicators — all point to a single entry at the same moment",
      "When the market opens and closes at the same price",
      "When your buy and sell orders execute simultaneously",
    ],
    answer: 1,
    explanation: "Look for the bull's-eye: a single point where price level, time cycle, and technical indicators all converge to signal an entry. The market is trying to tell you something.",
  },
  {
    id: 10,
    bookId: 6,
    chapter: null,
    topic: "Rule #14",
    question: "Rule #14: 'Control risk before seeking reward.' The author says 'attention to profit is a sign of immaturity.' Why?",
    options: [
      "Because profits don't matter in trading",
      "Because experienced traders focus on managing losses first — the profits take care of themselves when risk is controlled",
      "Because immature traders make more money",
      "Because you should never think about profits",
    ],
    answer: 1,
    explanation: "Attention to profit = immaturity. Attention to loss = experience. The markets have no intention of offering money to those who don't earn it through risk management.",
  },
  {
    id: 11,
    bookId: 6,
    chapter: null,
    topic: "Rule #15",
    question: "Rule #15: 'Big losses rarely come without warning.' Who does the author blame for big losses?",
    options: [
      "The market makers",
      "The broker",
      "Yourself — the chart told you to leave, the news told you to leave, and you ignored the warnings",
      "Bad luck",
    ],
    answer: 2,
    explanation: "You have no one to blame but yourself. The chart, the news, and even your instincts all warned you. Learn to visualize trouble and head for safety with only a few bars of data.",
  },
  {
    id: 12,
    bookId: 6,
    chapter: null,
    topic: "Rule #16",
    question: "Rule #16: 'Bulls live above the 200-day moving average while bears live below it.' What divides the investing world in two?",
    options: [
      "The S&P 500 index level",
      "The 200-day moving average — bulls and greed above it, bears and fear below it",
      "Whether the Fed is raising or cutting rates",
      "The VIX level",
    ],
    answer: 1,
    explanation: "The 200-day MA is the dividing line. Sellers eat up rallies below it, buyers rescue dips above it. Know which side you're on before entering any trade.",
  },
  {
    id: 13,
    bookId: 6,
    chapter: null,
    topic: "Rule #17",
    question: "Rule #17: 'Enter in mild times, exit in wild times.' Where does the big move hide?",
    options: [
      "In the first minute of trading",
      "Just beyond the extremes of the trading range — enter during the quiet, exit during the chaos",
      "In after-hours trading only",
      "In penny stocks",
    ],
    answer: 1,
    explanation: "The big move hides beyond the range extremes. Don't count on the agitated crowd for entry signals — it's too late by the time they act. Enter the quiet, exit the storm.",
  },
  {
    id: 14,
    bookId: 6,
    chapter: null,
    topic: "Rule #18",
    question: "Rule #18: 'Perfect patterns carry the greatest risk for failure.' What does the author warn about clean setups?",
    options: [
      "Perfect patterns always work",
      "The prettiest patterns set up the most painful losses — if it looks too good to be true, it probably is",
      "Only trade perfect patterns",
      "Perfect patterns only work in bull markets",
    ],
    answer: 1,
    explanation: "Demand warts and bruises on your trade setups. When a pattern looks too perfect, everyone sees it — and the crowd is usually wrong. If it looks too good to be true, it probably is.",
  },
  {
    id: 15,
    bookId: 6,
    chapter: null,
    topic: "Rule #20",
    question: "Rule #20: 'See the exit door before the trade.' What should you assume the moment you get filled?",
    options: [
      "That the trade will be profitable",
      "That the market will reverse against you immediately — always know your exit before you enter",
      "That you should add to the position",
      "That you can relax and wait",
    ],
    answer: 1,
    explanation: "Assume the market will reverse the minute you get filled. If it's a long way to the exit door, you're in big trouble. Never enter without knowing exactly where you'll get out.",
  },
  {
    id: 16,
    bookId: 6,
    chapter: null,
    topic: "Rule #22",
    question: "Rule #22: 'Don't believe in a company or its fundamentals.' What's the difference between trading and investing?",
    options: [
      "There is no difference",
      "Trading is about price action and numbers — forget the company story and press releases, that's for investors like Peter Lynch",
      "Trading is easier than investing",
      "Traders should only buy companies they love",
    ],
    answer: 1,
    explanation: "Trading is not investment. Remember the numbers and forget the press releases. You can love a company as an investor but as a trader, you only care about the chart.",
  },
  {
    id: 17,
    bookId: 6,
    chapter: null,
    topic: "Rule #24",
    question: "Rule #24: 'Don't try to get even.' What does the author say about revenge trading?",
    options: [
      "It's a great way to recover losses",
      "Trading is never a game of catch-up — every position must stand on its own merits, taken with composure and absolute discipline",
      "You should always try to make back what you lost",
      "Getting even is the fastest way to profitability",
    ],
    answer: 1,
    explanation: "Take your loss with composure and take the next trade with absolute discipline. Every position must stand on its own merits — it's never a game of catch-up.",
  },
  {
    id: 18,
    bookId: 6,
    chapter: null,
    topic: "Rule #26",
    question: "Rule #26: 'Don't seek the Holy Grail.' What is the only 'secret formula' in trading?",
    options: [
      "A proprietary algorithm",
      "Solid risk management — there is no secret trading formula other than that",
      "The Fibonacci sequence",
      "A subscription to the right newsletter",
    ],
    answer: 1,
    explanation: "There is no secret trading formula, other than solid risk management. Stop looking for the magic indicator or system — manage your risk and the rest follows.",
  },
  {
    id: 19,
    bookId: 6,
    chapter: null,
    topic: "Rule #27",
    question: "Rule #27: 'Don't forget your discipline.' Why do most traders fail, according to the author?",
    options: [
      "Lack of capital",
      "Lack of knowledge",
      "Lack of discipline — learning the basics is easy, but sticking to the rules is where most traders fail",
      "Bad luck",
    ],
    answer: 2,
    explanation: "Learning the basics is easy. Most traders fail due to a lack of discipline, not a lack of knowledge. The rules are simple — following them consistently is the hard part.",
  },
  {
    id: 20,
    bookId: 6,
    chapter: null,
    topic: "Rule #30",
    question: "Rule #30: 'Don't think it's entertainment.' What will successful trading feel like most of the time?",
    options: [
      "Exciting and thrilling every day",
      "Like winning the lottery",
      "Boring — just like the real job you have now",
      "Like playing a video game",
    ],
    answer: 2,
    explanation: "Successful trading will be boring most of the time, just like any real job. If you're trading for excitement, you're gambling. Boredom + discipline = profitability.",
  },
];
