/**
 * Book 0 — General Basics (Trader University Guides)
 *
 * Questions sourced from:
 *   - Beginner Day Trader Roadmap
 *   - Futures Terms Guide
 *   - Wash Sale Rule Guide
 */

import type { QuizQuestion } from "./types";

export const BOOK_00_META = {
  id: 0,
  title: "General Trading Basics",
  shortTitle: "General Basics",
};

export const BOOK_00_QUESTIONS: QuizQuestion[] = [
  // ── Day Trading Basics ─────────────────────────────────────────────
  {
    id: 1,
    bookId: 0,
    chapter: null,
    topic: "Day Trading Basics",
    question: "What is the main focus of day trading?",
    options: [
      "Holding positions for weeks or months",
      "Profiting from intraday price movement",
      "Collecting dividends from stocks",
      "Buying and holding index funds",
    ],
    answer: 1,
    explanation: "Day trading focuses on buying and selling within the same trading day to profit from intraday price movement.",
  },
  {
    id: 2,
    bookId: 0,
    chapter: null,
    topic: "Day Trading Basics",
    question: "According to the Beginner Roadmap, what should you do BEFORE going live with real money?",
    options: [
      "Deposit at least $25,000",
      "Subscribe to a stock picking service",
      "Backtest and paper trade your strategy",
      "Buy the most popular stock on social media",
    ],
    answer: 2,
    explanation: "Step 7 of the Roadmap: backtest historical charts and practice in real time using paper trading before risking real money.",
  },
  {
    id: 3,
    bookId: 0,
    chapter: null,
    topic: "Day Trading Basics",
    question: "What is the recommended maximum risk per trade for a beginner day trader?",
    options: [
      "10% of your account",
      "5% of your account",
      "1% of your account",
      "50% of your account",
    ],
    answer: 2,
    explanation: "The Roadmap recommends a max 1% per trade, 3% per day risk rule to protect your capital.",
  },
  {
    id: 4,
    bookId: 0,
    chapter: null,
    topic: "Day Trading Basics",
    question: "What is the recommended maximum daily risk for a beginner?",
    options: [
      "3% of your account",
      "10% of your account",
      "25% of your account",
      "No limit — keep trading until you make it back",
    ],
    answer: 0,
    explanation: "The 1% per trade / 3% per day rule helps prevent catastrophic drawdowns early in your trading career.",
  },
  {
    id: 5,
    bookId: 0,
    chapter: null,
    topic: "Day Trading Basics",
    question: "Why is journaling every trade important?",
    options: [
      "The IRS requires it for all traders",
      "It helps you track entries, exits, setups, emotions, and lessons",
      "Your broker will close your account without a journal",
      "It replaces the need for a trading plan",
    ],
    answer: 1,
    explanation: "Step 9: journaling helps you identify patterns in your behavior, learn from mistakes, and track progress over time.",
  },
  {
    id: 6,
    bookId: 0,
    chapter: null,
    topic: "Day Trading Basics",
    question: "What does 'mastering your psychology' as a trader mean?",
    options: [
      "Never feeling any emotions while trading",
      "Avoiding FOMO, revenge trades, and overtrading",
      "Only trading when you feel lucky",
      "Ignoring your losses completely",
    ],
    answer: 1,
    explanation: "Step 10: emotional discipline means recognizing and controlling destructive behaviors like FOMO and revenge trading.",
  },

  // ── Market Sessions & Order Types ──────────────────────────────────
  {
    id: 7,
    bookId: 0,
    chapter: null,
    topic: "Market Sessions",
    question: "What are the regular US stock market trading hours (Eastern Time)?",
    options: [
      "8:00 AM – 4:00 PM",
      "9:30 AM – 4:00 PM",
      "9:00 AM – 3:30 PM",
      "7:00 AM – 5:00 PM",
    ],
    answer: 1,
    explanation: "Regular trading hours for NYSE and NASDAQ are 9:30 AM to 4:00 PM Eastern Time.",
  },
  {
    id: 8,
    bookId: 0,
    chapter: null,
    topic: "Market Sessions",
    question: "What is 'pre-market' trading?",
    options: [
      "Trading that happens before you open your broker app",
      "Trading before regular market hours, typically starting at 4:00 AM ET",
      "A simulated practice environment",
      "Trading only available to institutional investors",
    ],
    answer: 1,
    explanation: "Pre-market trading occurs before 9:30 AM ET, typically starting at 4:00 AM, with lower liquidity and wider spreads.",
  },
  {
    id: 9,
    bookId: 0,
    chapter: null,
    topic: "Market Sessions",
    question: "What type of order guarantees execution but NOT the price?",
    options: [
      "Limit order",
      "Stop-limit order",
      "Market order",
      "Trailing stop order",
    ],
    answer: 2,
    explanation: "A market order fills immediately at the best available price, guaranteeing execution but not a specific price.",
  },
  {
    id: 10,
    bookId: 0,
    chapter: null,
    topic: "Market Sessions",
    question: "What type of order lets you set the maximum price you're willing to pay?",
    options: [
      "Market order",
      "Limit order",
      "Stop order",
      "Fill-or-kill order",
    ],
    answer: 1,
    explanation: "A limit order specifies the maximum buy price (or minimum sell price), but may not fill if the market doesn't reach your price.",
  },
  {
    id: 11,
    bookId: 0,
    chapter: null,
    topic: "Market Sessions",
    question: "What is the Pattern Day Trader (PDT) rule?",
    options: [
      "You must trade at least 4 times per week",
      "Accounts under $25,000 are limited to 3 day trades in 5 business days",
      "You can only day trade penny stocks",
      "You need a special license to day trade",
    ],
    answer: 1,
    explanation: "FINRA's PDT rule restricts accounts under $25,000 to 3 day trades per rolling 5-business-day period.",
  },
  {
    id: 12,
    bookId: 0,
    chapter: null,
    topic: "Market Sessions",
    question: "Why is liquidity typically lower during pre-market and after-hours sessions?",
    options: [
      "The exchanges are closed",
      "Only market makers can trade",
      "Fewer participants are trading, leading to wider spreads",
      "Stocks are frozen during those times",
    ],
    answer: 2,
    explanation: "Extended hours have fewer active traders, resulting in lower volume, wider bid-ask spreads, and more volatile price swings.",
  },

  // ── Technical Analysis ─────────────────────────────────────────────
  {
    id: 13,
    bookId: 0,
    chapter: null,
    topic: "Technical Analysis",
    question: "What does VWAP stand for?",
    options: [
      "Value Weighted Asset Price",
      "Volume Weighted Average Price",
      "Volatility Weighted Annual Percentage",
      "Variable Width Average Pattern",
    ],
    answer: 1,
    explanation: "VWAP (Volume Weighted Average Price) is an intraday benchmark that shows the average price weighted by volume.",
  },
  {
    id: 14,
    bookId: 0,
    chapter: null,
    topic: "Technical Analysis",
    question: "If a stock is trading ABOVE VWAP, what does that generally indicate?",
    options: [
      "Bearish sentiment — sellers are in control",
      "The stock is about to be halted",
      "Bullish sentiment — intraday buyers are in control",
      "The stock has low volume",
    ],
    answer: 2,
    explanation: "Trading above VWAP means buyers have been more aggressive on average, indicating intraday bullish control.",
  },
  {
    id: 15,
    bookId: 0,
    chapter: null,
    topic: "Technical Analysis",
    question: "What are common EMA periods used by day traders according to the Roadmap?",
    options: [
      "3, 7, and 14",
      "9, 21, and 55",
      "100, 200, and 500",
      "1, 2, and 3",
    ],
    answer: 1,
    explanation: "The Roadmap lists VWAP, EMAs (9, 21, 55), EWO, Volume, MA200, and Super Trend as key indicators to study.",
  },
  {
    id: 16,
    bookId: 0,
    chapter: null,
    topic: "Technical Analysis",
    question: "What is a 'support level'?",
    options: [
      "A price level where a stock tends to stop falling and bounce",
      "The highest price a stock has ever reached",
      "A price level set by the SEC",
      "The price where your broker blocks your order",
    ],
    answer: 0,
    explanation: "Support is a price level where buying interest tends to prevent further decline, creating a 'floor' for the price.",
  },
  {
    id: 17,
    bookId: 0,
    chapter: null,
    topic: "Technical Analysis",
    question: "What is a 'breakout' setup?",
    options: [
      "When a stock splits into two tickers",
      "When price moves through a key resistance level with volume",
      "When a stock drops 50% in one day",
      "When you break out of a losing streak",
    ],
    answer: 1,
    explanation: "A breakout occurs when price pushes through resistance with conviction (volume), often signaling a new trend leg.",
  },
  {
    id: 18,
    bookId: 0,
    chapter: null,
    topic: "Technical Analysis",
    question: "What is a 'bull flag' pattern?",
    options: [
      "A flag that appears on bullish news headlines",
      "A sharp move up followed by a slight consolidation, suggesting continuation higher",
      "A pattern that only appears on monthly charts",
      "When the stock price forms the letter F on the chart",
    ],
    answer: 1,
    explanation: "A bull flag is a continuation pattern — a strong upward move (flagpole) followed by a tight consolidation before the next leg up.",
  },

  // ── Futures Basics ─────────────────────────────────────────────────
  {
    id: 19,
    bookId: 0,
    chapter: null,
    topic: "Futures Basics",
    question: "What is a futures contract?",
    options: [
      "A loan from your broker to trade stocks",
      "An agreement to buy or sell an asset at a predetermined price on a future date",
      "A stock that will be listed in the future",
      "A savings bond issued by the government",
    ],
    answer: 1,
    explanation: "A futures contract obligates the buyer to purchase and the seller to sell an asset at a set price on a specific future date.",
  },
  {
    id: 20,
    bookId: 0,
    chapter: null,
    topic: "Futures Basics",
    question: "What is 'margin' in futures trading?",
    options: [
      "The profit you make on a trade",
      "The money required to open and maintain a futures position, acting as a security deposit",
      "The space between the bid and ask price",
      "The commission your broker charges",
    ],
    answer: 1,
    explanation: "Margin is a security deposit ensuring you can fulfill the contract, not the full value of the position.",
  },
  {
    id: 21,
    bookId: 0,
    chapter: null,
    topic: "Futures Basics",
    question: "What happens if your account falls below the 'maintenance margin'?",
    options: [
      "Your account is automatically closed",
      "You receive a margin call and must add funds",
      "The exchange adds money to your account",
      "Nothing — it only matters at expiration",
    ],
    answer: 1,
    explanation: "Falling below maintenance margin triggers a margin call — you must deposit additional funds or your position may be liquidated.",
  },
  {
    id: 22,
    bookId: 0,
    chapter: null,
    topic: "Futures Basics",
    question: "What does 'going long' in futures mean?",
    options: [
      "Holding a position for a long time",
      "Buying a contract expecting the price will rise",
      "Selling a contract expecting the price will fall",
      "Borrowing shares from your broker",
    ],
    answer: 1,
    explanation: "Going long = buying. You profit when the underlying asset's price rises above your entry price.",
  },
  {
    id: 23,
    bookId: 0,
    chapter: null,
    topic: "Futures Basics",
    question: "What does 'going short' in futures mean?",
    options: [
      "Holding a position for a short time",
      "Buying a contract with a short expiration",
      "Selling a contract expecting the price will fall",
      "Trading micro contracts instead of full-size",
    ],
    answer: 2,
    explanation: "Going short = selling. You profit when the underlying asset's price falls below your entry price.",
  },
  {
    id: 24,
    bookId: 0,
    chapter: null,
    topic: "Futures Basics",
    question: "What is 'open interest' in futures?",
    options: [
      "How interested traders are in a contract",
      "The total number of outstanding contracts that have not been settled",
      "The interest rate charged on margin",
      "The number of people watching a ticker",
    ],
    answer: 1,
    explanation: "Open interest measures the total number of active contracts, indicating market activity and liquidity.",
  },

  // ── Wash Sale Rule ─────────────────────────────────────────────────
  {
    id: 25,
    bookId: 0,
    chapter: null,
    topic: "Wash Sale Rule",
    question: "What is the wash sale rule?",
    options: [
      "You must wash your hands before trading",
      "You cannot sell and rebuy a substantially identical security within 30 days and claim the tax loss",
      "You must hold a stock for 30 days before selling",
      "All trading losses are tax-deductible without limits",
    ],
    answer: 1,
    explanation: "The wash sale rule prevents you from claiming a tax loss if you repurchase the same or similar security within 30 days.",
  },
  {
    id: 26,
    bookId: 0,
    chapter: null,
    topic: "Wash Sale Rule",
    question: "If a wash sale occurs, what happens to the disallowed loss?",
    options: [
      "It is permanently lost and cannot be recovered",
      "It is added to the cost basis of the newly purchased security",
      "The IRS sends you a refund",
      "It carries forward as a capital gains credit",
    ],
    answer: 1,
    explanation: "The disallowed loss is added to the cost basis of the new shares, deferring (not eliminating) the tax benefit.",
  },
  {
    id: 27,
    bookId: 0,
    chapter: null,
    topic: "Wash Sale Rule",
    question: "What does 'substantially identical' mean in the wash sale rule?",
    options: [
      "Any stock in the same industry",
      "Any security listed on the same exchange",
      "The same stock, or a very similar security like options on the same stock",
      "Any security you have traded before",
    ],
    answer: 2,
    explanation: "Substantially identical includes the same stock and close derivatives like options on that stock or funds tracking the same index.",
  },
  {
    id: 28,
    bookId: 0,
    chapter: null,
    topic: "Wash Sale Rule",
    question: "You sell 100 shares of XYZ at a $50 loss, then buy XYZ back 15 days later. Can you deduct the $50 loss this year?",
    options: [
      "Yes — you already sold the shares",
      "Yes — but only half the loss",
      "No — this is a wash sale because you repurchased within 30 days",
      "No — losses on stocks are never tax-deductible",
    ],
    answer: 2,
    explanation: "Repurchasing the same security within 30 days triggers a wash sale — the $50 loss is added to the new shares' cost basis instead.",
  },
  {
    id: 29,
    bookId: 0,
    chapter: null,
    topic: "Wash Sale Rule",
    question: "Does the wash sale rule apply to transactions in retirement accounts (IRA, 401k)?",
    options: [
      "No — retirement accounts are fully exempt",
      "Yes — selling at a loss in a taxable account and buying in an IRA within 30 days still triggers it",
      "Only if the retirement account is a Roth IRA",
      "Only if you are over 59½ years old",
    ],
    answer: 1,
    explanation: "Buying in an IRA within 30 days of a taxable loss sale still triggers the wash sale rule, and in this case the loss may be permanently disallowed.",
  },
  {
    id: 30,
    bookId: 0,
    chapter: null,
    topic: "Wash Sale Rule",
    question: "What is the purpose of the wash sale rule?",
    options: [
      "To prevent traders from claiming artificial tax losses while maintaining the same position",
      "To force traders to diversify their portfolio",
      "To limit the number of trades per day",
      "To prevent insider trading",
    ],
    answer: 0,
    explanation: "The rule stops people from selling at a loss for a tax break and immediately rebuying to keep their position unchanged.",
  },
];
