/**
 * Book 1 — Day Trading for Dummies
 *
 * 30 questions across 3 chapter groups:
 *   Chapter group 1: Fundamentals & Getting Started (Ch 1-4, 17-18)
 *   Chapter group 2: Tools, Psychology & Money Management (Ch 5-11)
 *   Chapter group 3: Strategies & Market Indicators (Ch 12-16)
 */

import type { QuizQuestion } from "./types";

export const BOOK_01_META = {
  id: 1,
  title: "Day Trading for Dummies",
  shortTitle: "Day Trading for Dummies",
};

export const BOOK_01_QUESTIONS: QuizQuestion[] = [
  // ── Chapter Group 1: Fundamentals & Getting Started ────────────────

  {
    id: 1,
    bookId: 1,
    chapter: 1,
    topic: "Day Trading Fundamentals",
    question: "According to the book, approximately what percentage of day traders lose money?",
    options: [
      "About 50%",
      "About 60%",
      "About 80%",
      "About 95%",
    ],
    answer: 2,
    explanation: "The book states that about 80% of day traders lose money, making discipline and preparation critical.",
  },
  {
    id: 2,
    bookId: 1,
    chapter: 1,
    topic: "Day Trading Fundamentals",
    question: "What is the key distinction between day trading, swing trading, and investing?",
    options: [
      "The amount of money you trade with",
      "The time horizon — day traders close all positions by end of day",
      "The type of securities you trade",
      "Whether you use a broker or trade directly",
    ],
    answer: 1,
    explanation: "Day traders close all positions before the market closes. Swing traders hold days to weeks. Investors hold months to years.",
  },
  {
    id: 3,
    bookId: 1,
    chapter: 1,
    topic: "Day Trading Fundamentals",
    question: "The book compares day trading to which type of business?",
    options: [
      "A franchise restaurant",
      "A small business you run yourself",
      "A lottery with better odds",
      "A video game with real money",
    ],
    answer: 1,
    explanation: "The book emphasizes day trading is a small business — you're the boss, responsible for everything from strategy to accounting.",
  },
  {
    id: 4,
    bookId: 1,
    chapter: 4,
    topic: "Trading vs Investing vs Gambling",
    question: "According to the book, what is the difference between trading and gambling?",
    options: [
      "There is no difference — both are pure chance",
      "Traders use a tested system with an edge; gamblers rely on luck",
      "Gambling is regulated and trading is not",
      "Trading always makes money if you try hard enough",
    ],
    answer: 1,
    explanation: "The book stresses that trading requires a tested system with a statistical edge, while gambling relies on chance.",
  },
  {
    id: 5,
    bookId: 1,
    chapter: 4,
    topic: "Trading vs Investing vs Gambling",
    question: "What does the book say about day traders who treat trading like gambling?",
    options: [
      "They usually get lucky and make money",
      "They are the most successful traders",
      "They lose money and often develop destructive habits",
      "They should switch to options trading instead",
    ],
    answer: 2,
    explanation: "Trading without a system is gambling. The book warns it leads to losses and can spiral into destructive behavior.",
  },
  {
    id: 6,
    bookId: 1,
    chapter: 17,
    topic: "Readiness Assessment",
    question: "Which of these is NOT listed as a good reason to day trade?",
    options: [
      "You love being independent",
      "You have studied trading systems and know what works for you",
      "You want to get rich quick without preparation",
      "You can afford to lose money",
    ],
    answer: 2,
    explanation: "Chapter 17 lists 10 good reasons including independence, market knowledge, and financial cushion — but never promises quick riches.",
  },
  {
    id: 7,
    bookId: 1,
    chapter: 17,
    topic: "Readiness Assessment",
    question: "Why does the book say you need a 'walk-away fund' before day trading?",
    options: [
      "To pay for trading software",
      "To cover 3+ months of living expenses so you don't trade from desperation",
      "To meet the PDT rule requirements",
      "To pay for your trading education",
    ],
    answer: 1,
    explanation: "Walk-away money covers your living expenses so you can trade without fear or greed driving your decisions.",
  },
  {
    id: 8,
    bookId: 1,
    chapter: 18,
    topic: "Readiness Assessment",
    question: "Which of these is a warning sign that day trading might NOT be for you?",
    options: [
      "You enjoy working independently",
      "You have investing experience",
      "You crave excitement and action",
      "You are decisive and persistent",
    ],
    answer: 2,
    explanation: "Chapter 18 warns that craving excitement is dangerous — day trading is often boring, and seeking thrills leads to bad trades.",
  },
  {
    id: 9,
    bookId: 1,
    chapter: 18,
    topic: "Readiness Assessment",
    question: "The book warns against using day trading to learn investing. Why?",
    options: [
      "Day trading and investing use completely different markets",
      "Day trading focuses on short-term price movements, not company fundamentals",
      "Investing is illegal for day traders",
      "You need a different license for investing",
    ],
    answer: 1,
    explanation: "Day traders profit from short-term price movement and often don't care what a company does. Investing requires fundamental analysis.",
  },
  {
    id: 10,
    bookId: 1,
    chapter: 2,
    topic: "Markets & Securities",
    question: "According to the book, what is 'scalping'?",
    options: [
      "Buying stocks at their lowest point of the day",
      "Making a large number of quick trades for small price movements",
      "Reselling trading software at a markup",
      "Trading only during the first 5 minutes of market open",
    ],
    answer: 1,
    explanation: "Scalping involves making many rapid trades to capture tiny price movements. Speed and execution quality are critical.",
  },

  // ── Chapter Group 2: Tools, Psychology & Money Management ─────────

  {
    id: 11,
    bookId: 1,
    chapter: 8,
    topic: "Trading Psychology",
    question: "What are the 'big five emotions' that the book says hurt traders?",
    options: [
      "Happiness, sadness, surprise, disgust, anger",
      "Anxiety, boredom, depression, fear, greed",
      "Excitement, confidence, hope, love, pride",
      "Frustration, impatience, envy, regret, guilt",
    ],
    answer: 1,
    explanation: "Chapter 8 identifies anxiety, boredom, depression, fear, and greed as the five emotions that sabotage trading performance.",
  },
  {
    id: 12,
    bookId: 1,
    chapter: 8,
    topic: "Trading Psychology",
    question: "What is 'choking' in trading, according to the book?",
    options: [
      "Running out of buying power mid-trade",
      "Over-thinking your plan so much that trades become slow and deliberate, and you miss opportunities",
      "Getting a margin call",
      "Making too many trades in one day",
    ],
    answer: 1,
    explanation: "Choking means over-thinking causes you to execute too slowly and miss trades. The book advises trusting your tested plan.",
  },
  {
    id: 13,
    bookId: 1,
    chapter: 8,
    topic: "Trading Psychology",
    question: "What does the book say is the difference between confidence and ego in trading?",
    options: [
      "There is no difference",
      "Confidence = 'I can figure out what the market is telling me'; Ego = 'I'm smarter than the market'",
      "Confidence means risking more money; ego means risking less",
      "Confident traders never lose; ego-driven traders always lose",
    ],
    answer: 1,
    explanation: "Confidence is trusting your process. Ego is believing you're smarter than the market — a dangerous mindset that leads to overtrading.",
  },
  {
    id: 14,
    bookId: 1,
    chapter: 8,
    topic: "Trading Psychology",
    question: "The book says 'Pigs get fat, but hogs get slaughtered.' What emotion does this address?",
    options: [
      "Fear",
      "Anxiety",
      "Greed",
      "Boredom",
    ],
    answer: 2,
    explanation: "This Chicago Board of Trade saying warns against greed — holding too long, trading too big, or abandoning your plan for more profit.",
  },
  {
    id: 15,
    bookId: 1,
    chapter: 9,
    topic: "Money Management",
    question: "What is 'expected return' in trading?",
    options: [
      "The amount your broker guarantees you will earn",
      "The average profit per trade based on win rate, win size, loss rate, and loss size",
      "The interest rate on your margin account",
      "The minimum amount you need to start trading",
    ],
    answer: 1,
    explanation: "Expected return = (% losers × avg loss) + (% winners × avg gain). A positive expected return means the system should be profitable over time.",
  },
  {
    id: 16,
    bookId: 1,
    chapter: 9,
    topic: "Money Management",
    question: "What is 'fixed fractional' money management?",
    options: [
      "Trading the same dollar amount on every trade",
      "Limiting each trade to a fixed percentage of your total account (e.g. 2-10%)",
      "Only trading fractional shares",
      "Splitting your account into exactly 5 equal parts",
    ],
    answer: 1,
    explanation: "Fixed fractional trading risks a set percentage of your account per trade, adjusting position size based on account value and trade risk.",
  },
  {
    id: 17,
    bookId: 1,
    chapter: 9,
    topic: "Money Management",
    question: "What is the 'probability of ruin'?",
    options: [
      "The chance your broker goes bankrupt",
      "The chance of losing your entire trading account over time",
      "The probability that a single trade loses money",
      "The likelihood of a market crash",
    ],
    answer: 1,
    explanation: "Probability of ruin measures your chance of going broke. Smaller trade sizes and a higher edge reduce this probability.",
  },
  {
    id: 18,
    bookId: 1,
    chapter: 9,
    topic: "Money Management",
    question: "What is the Kelly Criterion used for?",
    options: [
      "Determining which stocks to buy",
      "Calculating the ideal percentage of your portfolio to risk per trade",
      "Measuring market volatility",
      "Calculating your tax liability",
    ],
    answer: 1,
    explanation: "The Kelly Criterion (Kelly % = W - [(1-W) / R]) determines optimal position sizing. Many traders use 'half-Kelly' to be more conservative.",
  },
  {
    id: 19,
    bookId: 1,
    chapter: 9,
    topic: "Money Management",
    question: "Why does the book warn against the 'martingale' strategy?",
    options: [
      "It's illegal in the US markets",
      "It requires doubling your bet after each loss, which can wipe you out before you recover",
      "It only works with options, not stocks",
      "It's too complicated for beginners",
    ],
    answer: 1,
    explanation: "Martingale doubles your position after losses. While it works with infinite money, you'll run out of capital before the winning trade comes.",
  },
  {
    id: 20,
    bookId: 1,
    chapter: 11,
    topic: "Performance Evaluation",
    question: "According to the book, what is 'backtesting'?",
    options: [
      "Trading with a backup account",
      "Running your strategy against historical price data to see if it would have been profitable",
      "Testing your internet connection speed",
      "Reviewing trades you already made",
    ],
    answer: 1,
    explanation: "Backtesting runs your strategy rules against past data. The book warns about curve-fitting — results that look great historically but don't work live.",
  },

  // ── Chapter Group 3: Strategies & Market Indicators ────────────────

  {
    id: 21,
    bookId: 1,
    chapter: 13,
    topic: "Market Indicators",
    question: "What is a 'momentum oscillator'?",
    options: [
      "A tool that measures how fast your internet connection is",
      "An indicator that measures the rate of price change, showing overbought/oversold conditions",
      "A type of trading order",
      "A measure of how many people are watching a stock",
    ],
    answer: 1,
    explanation: "Momentum oscillators track the rate of price change. Above the center line = overbought; below = oversold.",
  },
  {
    id: 22,
    bookId: 1,
    chapter: 13,
    topic: "Market Indicators",
    question: "What does the 'trin' (trading indicator) measure?",
    options: [
      "The total number of trades in a day",
      "Market sentiment by comparing advancing/declining stocks with their volume",
      "The average commission cost",
      "How many traders are online",
    ],
    answer: 1,
    explanation: "Trin = (advances/declines) / (advance volume/decline volume). Below 1.0 = bullish (buyers dominating); above 1.0 = bearish.",
  },
  {
    id: 23,
    bookId: 1,
    chapter: 13,
    topic: "Market Indicators",
    question: "What is 'on-balance volume' (OBV)?",
    options: [
      "The average volume over the past 10 days",
      "A running total that adds volume on up days and subtracts volume on down days",
      "The volume of shares available to short",
      "The balance in your trading account",
    ],
    answer: 1,
    explanation: "OBV tracks cumulative volume flow. Rising OBV with flat price can signal that smart money is accumulating before a price move.",
  },
  {
    id: 24,
    bookId: 1,
    chapter: 13,
    topic: "Market Indicators",
    question: "What does the VIX measure?",
    options: [
      "The average volume of the top 500 stocks",
      "Expected volatility of the S&P 500, often called the 'fear gauge'",
      "The speed of trade execution",
      "The number of day traders active in the market",
    ],
    answer: 1,
    explanation: "The VIX measures implied volatility of S&P 500 options. Higher VIX = more fear/uncertainty. Some consider it a market fear gauge.",
  },
  {
    id: 25,
    bookId: 1,
    chapter: 13,
    topic: "Market Indicators",
    question: "What is a 'contrarian trap'?",
    options: [
      "When the market tricks you into selling at the bottom",
      "When you trade against the trend and lose because the market is always right in the short term",
      "When two opposite indicators give the same signal",
      "When your broker changes your order type",
    ],
    answer: 1,
    explanation: "Going against the trend can be profitable long-term but is dangerous for day traders. In a single session, the market's direction usually wins.",
  },
  {
    id: 26,
    bookId: 1,
    chapter: 13,
    topic: "Market Indicators",
    question: "What is 'beta' in the context of a stock?",
    options: [
      "The second version of a trading strategy",
      "A measure of how much a stock moves relative to the overall market",
      "The minimum price movement of a stock",
      "A stock that is still in testing phase before IPO",
    ],
    answer: 1,
    explanation: "Beta > 1 = moves faster than the market. Beta < 1 = moves slower. Beta = 1 = moves with the market. Negative beta = moves opposite.",
  },
  {
    id: 27,
    bookId: 1,
    chapter: 13,
    topic: "Market Indicators",
    question: "According to the book, what is an 'order imbalance'?",
    options: [
      "When your buy and sell orders don't match in size",
      "When the number of buyers and sellers in the market don't match, often at market open",
      "When you place too many orders in one day",
      "When your account has more losses than wins",
    ],
    answer: 1,
    explanation: "Order imbalances happen when buy/sell orders don't match, often at the open. Large imbalances can halt trading until orders balance out.",
  },
  {
    id: 28,
    bookId: 1,
    chapter: 9,
    topic: "Money Management",
    question: "What is 'pyramiding' in trading?",
    options: [
      "A type of investment scam",
      "Using unrealized profits from winning trades as collateral to open additional positions during the day",
      "Buying the same stock every day for a month",
      "Spreading trades across 3 different brokers",
    ],
    answer: 1,
    explanation: "Pyramiding uses intraday profits to take larger positions. It magnifies both gains and losses — the book warns it can destroy your account if reversed.",
  },
  {
    id: 29,
    bookId: 1,
    chapter: 11,
    topic: "Performance Evaluation",
    question: "The book warns about 'curve-fitting' in backtesting. What is it?",
    options: [
      "Making your charts look more visually appealing",
      "Over-optimizing a strategy to fit past data perfectly, producing results that don't work in live trading",
      "Fitting your trading screen to your monitor size",
      "Adjusting your position size to match your account curve",
    ],
    answer: 1,
    explanation: "Curve-fitting creates a strategy that works perfectly on historical data by incorporating too many variables, but fails in real markets.",
  },
  {
    id: 30,
    bookId: 1,
    chapter: 11,
    topic: "Performance Evaluation",
    question: "What does the book recommend you track in a trading diary?",
    options: [
      "Only your profitable trades",
      "Why you entered, why you exited, whether you followed your system, and your emotions",
      "Just the ticker symbols and dates",
      "Only trades where you lost money",
    ],
    answer: 1,
    explanation: "A trading diary captures entry/exit reasoning, whether you followed your plan, and emotional state — helping you identify patterns in your behavior.",
  },
];
