/**
 * Book 5 — Moving Averages 101 (Steve & Holly Burns)
 *
 * 20 questions across 2 chapter groups:
 *   Group 1: MA Types & Individual MAs (Ch 1-8)
 *   Group 2: Crossover Systems & Combining with Other Indicators (Ch 9-10)
 */

import type { QuizQuestion } from "./types";

export const BOOK_05_META = {
  id: 5,
  title: "Moving Averages 101",
  shortTitle: "Moving Averages 101",
};

export const BOOK_05_QUESTIONS: QuizQuestion[] = [
  // ── Group 1: MA Types & Individual MAs (Ch 1-8) ────────────────────

  {
    id: 1,
    bookId: 5,
    chapter: 1,
    topic: "MA Fundamentals",
    question: "What is the key difference between a Simple Moving Average (SMA) and an Exponential Moving Average (EMA)?",
    options: [
      "SMAs are for stocks, EMAs are for futures",
      "An SMA weights all prices equally; an EMA gives more weight to recent prices, making it react faster",
      "An EMA is always slower than an SMA",
      "There is no practical difference between them",
    ],
    answer: 1,
    explanation: "The SMA treats all prices equally. The EMA gives greater weight to recent prices, making it more reactive to current price action.",
  },
  {
    id: 2,
    bookId: 5,
    chapter: 1,
    topic: "MA Fundamentals",
    question: "According to the book, why are moving averages better than trend lines?",
    options: [
      "Moving averages are prettier on charts",
      "Trend lines are subjective (drawn by hand), while moving averages are quantifiable facts based on actual price data",
      "Trend lines don't work on daily charts",
      "Moving averages predict the future better",
    ],
    answer: 1,
    explanation: "The book emphasizes that trend lines are subjective and opinion-based, while MAs are unbiased, quantifiable trend indicators based on real price data.",
  },
  {
    id: 3,
    bookId: 5,
    chapter: 1,
    topic: "MA Fundamentals",
    question: "The author's 'moving average answer key' lists which six MAs as his core set?",
    options: [
      "3, 7, 14, 28, 56, 112 day",
      "5 EMA, 10 EMA, 21 EMA, 50 SMA, 100 SMA, 200 SMA",
      "10, 20, 30, 40, 50, 60 day SMA",
      "Only the 50 and 200 day SMA",
    ],
    answer: 1,
    explanation: "The author uses: 5-day EMA (momentum), 10-day EMA (short-term trend), 21-day EMA (pullback support), 50-day SMA (uptrend defense), 100-day SMA (oversold), 200-day SMA (bull's last stand).",
  },
  {
    id: 4,
    bookId: 5,
    chapter: 3,
    topic: "5-Day EMA",
    question: "What is the 5-day EMA best used for, according to the book?",
    options: [
      "Long-term investing decisions",
      "A strong momentum indicator, trailing stop after a breakout, and end-of-day stop in trending markets",
      "Identifying oversold conditions",
      "Determining which stocks to buy for retirement",
    ],
    answer: 1,
    explanation: "The 5-day EMA tracks the strongest short-term momentum. It's best used as a trailing stop after entering on a longer-term MA signal like the 50 or 200 day.",
  },
  {
    id: 5,
    bookId: 5,
    chapter: 3,
    topic: "5-Day EMA",
    question: "When does the 5-day EMA NOT work well?",
    options: [
      "In strong uptrends",
      "In range-bound markets, when prices are highly volatile, or when price penetrates the 5-day EMA daily",
      "In downtrends",
      "On daily charts",
    ],
    answer: 1,
    explanation: "The 5-day EMA only works in strongly trending markets. In choppy, range-bound, or highly volatile conditions, price crosses it constantly — generating false signals.",
  },
  {
    id: 6,
    bookId: 5,
    chapter: 4,
    topic: "10-Day EMA",
    question: "The author calls the 10-day EMA 'red light, green light.' What does this mean?",
    options: [
      "It changes color on the chart",
      "Above the 10-day EMA = green light (bullish, think buy); below = red light (bearish, think sell)",
      "You should only trade at traffic lights",
      "It alternates between profitable and unprofitable trades",
    ],
    answer: 1,
    explanation: "Marty Schwartz's quote: trading above the 10-day = green light (positive mode, think buy). Below = red light (negative mode, think sell).",
  },
  {
    id: 7,
    bookId: 5,
    chapter: 4,
    topic: "10-Day EMA",
    question: "When should the 10-day EMA only be used as a long signal, according to the book?",
    options: [
      "Always — it works as a long signal in all conditions",
      "Only when the long-term trend is up as measured by price being above the 200-day SMA",
      "Only on Mondays",
      "Only when volume is above average",
    ],
    answer: 1,
    explanation: "The 10-day EMA should be used as a long signal only above the 200-day SMA, and as a short signal only below it. This aligns short-term trades with the long-term trend.",
  },
  {
    id: 8,
    bookId: 5,
    chapter: 5,
    topic: "21-Day EMA",
    question: "What role does the 21-day EMA play in the author's system?",
    options: [
      "It's the fastest momentum indicator",
      "It marks the intermediate-term trend — the last line of support in a volatile uptrend before a deeper pullback",
      "It's only useful for options trading",
      "It replaces the 200-day SMA",
    ],
    answer: 1,
    explanation: "The 21-day EMA defines the intermediate trend. It gives trades more room to breathe without being stopped out by short-term noise, while filtering out intraday volatility.",
  },
  {
    id: 9,
    bookId: 5,
    chapter: 6,
    topic: "50-Day SMA",
    question: "The book calls the 50-day SMA the 'uptrend defense line.' What does it mean?",
    options: [
      "The SEC requires all stocks to stay above their 50-day SMA",
      "Strong leading stocks and bull markets typically pull back to the 50-day SMA and bounce — it's the 'buy the dip' level",
      "Stocks always stop falling at the 50-day SMA",
      "It's only useful for defensive stocks like utilities",
    ],
    answer: 1,
    explanation: "In strong uptrends, the 50-day SMA is where institutional buyers tend to step in. Most bull market pullbacks find support here — it's the classic 'buy the dip' level.",
  },
  {
    id: 10,
    bookId: 5,
    chapter: 6,
    topic: "50-Day SMA",
    question: "What happens when a stock that was above the 50-day SMA breaks below it in a downtrend?",
    options: [
      "It immediately recovers",
      "The 50-day SMA flips from support to resistance — rallies try to reach it but fail, confirming the downtrend",
      "Nothing significant happens",
      "The stock is automatically halted",
    ],
    answer: 1,
    explanation: "Once broken in a downtrend, the 50-day SMA becomes overhead resistance. Rallies try to reclaim it but fall short — a classic sign of distribution and downtrend continuation.",
  },

  // ── Group 2: Long-term MAs, Crossovers & Combining Indicators ─────

  {
    id: 11,
    bookId: 5,
    chapter: 7,
    topic: "100-Day SMA",
    question: "When does the 100-day SMA become most useful as an entry point?",
    options: [
      "Every time price touches it",
      "When it coincides with an oversold RSI reading of 30-35 during a bull market uptrend",
      "Only when the MACD is positive",
      "Never — it's not useful for entries",
    ],
    answer: 1,
    explanation: "The 100-day SMA offers the best risk/reward entries when it aligns with oversold RSI (30-35) in a market whose long-term trend is still up. Triple confirmation = high probability.",
  },
  {
    id: 12,
    bookId: 5,
    chapter: 8,
    topic: "200-Day SMA",
    question: "The book calls the 200-day SMA 'the bull's last stand.' What does the author say is the #1 takeaway from the entire course?",
    options: [
      "Always use the 5-day EMA",
      "A loss of the 200-day SMA is your first warning of a possible correction, downtrend, or bear market",
      "Only trade stocks above $100",
      "Moving averages predict the future",
    ],
    answer: 1,
    explanation: "The author says: 'If you take nothing else from this course — a loss of the 200 day is your first warning of a possible correction, downtrend, or bear market.' This alone can save you from large losses.",
  },
  {
    id: 13,
    bookId: 5,
    chapter: 8,
    topic: "200-Day SMA",
    question: "According to the book, what is the simplest long-term trading rule using the 200-day SMA?",
    options: [
      "Buy when the stock hits its 200-day SMA and sell when it bounces",
      "Stay long above the 200-day SMA, go to cash below it. Bull above, bear below.",
      "Short everything that crosses the 200-day SMA",
      "Ignore the 200-day SMA in bull markets",
    ],
    answer: 1,
    explanation: "Paul Tudor Jones: 'If it's above the 200 day, I'm gonna be long. If it's below, I'm either not gonna own it or I'm gonna be short it. Period, end of story.'",
  },
  {
    id: 14,
    bookId: 5,
    chapter: 8,
    topic: "200-Day SMA",
    question: "After a stock breaks below the 200-day SMA, what does the book say typically happens?",
    options: [
      "It immediately crashes to zero",
      "It tends to rally back to the 200-day SMA at least once before the real downtrend starts",
      "It recovers within a few days",
      "The broker automatically sells your position",
    ],
    answer: 1,
    explanation: "After breaking below the 200-day, a stock typically rallies back to test it from below (now resistance). This failed retest confirms the downtrend and provides a good short entry.",
  },
  {
    id: 15,
    bookId: 5,
    chapter: 9,
    topic: "Crossover Systems",
    question: "What is a moving average crossover system?",
    options: [
      "When you cross out MAs from your chart",
      "Enter when a shorter MA crosses above a longer MA, exit when it crosses back below — a mechanical trend-following method",
      "When two different stocks cross the same price",
      "A system that only uses one moving average",
    ],
    answer: 1,
    explanation: "Crossover systems use two MAs: buy when the fast crosses above the slow, sell when it crosses back below. It replaces opinions with quantifiable price action signals.",
  },
  {
    id: 16,
    bookId: 5,
    chapter: 9,
    topic: "Crossover Systems",
    question: "What is a 'Golden Cross'?",
    options: [
      "When the RSI crosses above 70",
      "When the 50-day SMA crosses up through the 200-day SMA — a signal of the beginning of a long-term bull market",
      "When gold price hits a new all-time high",
      "When two trend lines cross on a chart",
    ],
    answer: 1,
    explanation: "The Golden Cross (50-day SMA crossing above 200-day SMA) is one of the most watched signals for long-term trend followers. It signals a potential new bull market.",
  },
  {
    id: 17,
    bookId: 5,
    chapter: 9,
    topic: "Crossover Systems",
    question: "Why do crossover systems generate fewer signals than single moving averages?",
    options: [
      "Because they use slower internet connections",
      "Because requiring two MAs to agree filters out the noise — price can whipsaw through one MA 3-5 times while the crossover gives only one signal",
      "Because they only work once per month",
      "Because brokers limit the number of crossover trades",
    ],
    answer: 1,
    explanation: "Single MAs can be penetrated 3-5 times before trending. A crossover requires both to agree, filtering false signals and reducing losing trades in choppy markets.",
  },
  {
    id: 18,
    bookId: 5,
    chapter: 10,
    topic: "RSI + Moving Averages",
    question: "According to the book, what RSI level signals 'overbought' and is a good place to exit long trades?",
    options: [
      "50 RSI",
      "65-70 RSI for stock indexes and big-cap stocks",
      "90 RSI",
      "30 RSI",
    ],
    answer: 1,
    explanation: "The author uses 65-70 RSI as the overbought exit zone for longs, and 30-35 RSI as the oversold zone for covering shorts. At these extremes, risk/reward shifts against your position.",
  },
  {
    id: 19,
    bookId: 5,
    chapter: 10,
    topic: "MACD + Moving Averages",
    question: "How is the MACD calculated?",
    options: [
      "By adding the 50-day and 200-day SMAs",
      "By subtracting the 26-day EMA from the 12-day EMA, with a 9-day EMA signal line",
      "By dividing price by volume",
      "By averaging the RSI over 14 days",
    ],
    answer: 1,
    explanation: "MACD = 12-day EMA minus 26-day EMA. A 9-day EMA signal line is plotted on top. Crossovers of the MACD line over the signal line generate buy/sell signals.",
  },
  {
    id: 20,
    bookId: 5,
    chapter: 10,
    topic: "Combining Indicators",
    question: "What is the book's recommended approach for using MAs with RSI and MACD together?",
    options: [
      "Use all three to enter and exit simultaneously",
      "Use MAs and MACD crossovers for entries at the beginning of trends; use RSI to time exits by showing when the trend is extended",
      "Only use RSI, ignore MAs and MACD",
      "Use them on different stocks so they don't conflict",
    ],
    answer: 1,
    explanation: "MAs and MACD are best for entering at trend beginnings. RSI shows when the move is overextended — exit longs near 70 RSI, cover shorts near 30 RSI to maximize profits.",
  },
];
