/**
 * Book 3 — 25 Rules of Day Trading (Douglas E. Zalesky)
 *
 * 15 questions — short book covering all 25 rules of trading discipline.
 * The author's core thesis: trading discipline is 90% of the game.
 * Three spokes of the "Wheel of Success": Content, Mechanics, Discipline.
 */

import type { QuizQuestion } from "./types";

export const BOOK_03_META = {
  id: 3,
  title: "25 Rules of Day Trading",
  shortTitle: "25 Rules of Day Trading",
};

export const BOOK_03_QUESTIONS: QuizQuestion[] = [
  {
    id: 1,
    bookId: 3,
    chapter: null,
    topic: "Trading Discipline",
    question: "According to the author, what percentage of trading success comes from discipline?",
    options: [
      "50%",
      "70%",
      "90%",
      "100%",
    ],
    answer: 2,
    explanation: "The author states trading discipline is 90% of the game. Trade with discipline and you succeed; trade without it and you fail.",
  },
  {
    id: 2,
    bookId: 3,
    chapter: null,
    topic: "Wheel of Success",
    question: "What are the three spokes of the author's 'Wheel of Success'?",
    options: [
      "Money, Strategy, Luck",
      "Content, Mechanics, Discipline",
      "Charts, News, Volume",
      "Entry, Exit, Position Size",
    ],
    answer: 1,
    explanation: "Content = market information. Mechanics = how you execute trades. Discipline = the most important spoke — practiced 100% of the time.",
  },
  {
    id: 3,
    bookId: 3,
    chapter: null,
    topic: "Rule #3",
    question: "Rule #3 says: 'Always lower your trade size when you're trading poorly.' Why?",
    options: [
      "To save on commissions",
      "Because your broker requires it",
      "To stop the bleeding — like a batter shortening his swing after two strikeouts",
      "Because smaller trades always make more money",
    ],
    answer: 2,
    explanation: "After two losing trades in a row, drop to one lot. Get two winners, then size back up. It's about breaking the losing streak with minimal damage.",
  },
  {
    id: 4,
    bookId: 3,
    chapter: null,
    topic: "Rule #4",
    question: "Rule #4: 'Never turn a winner into a loser.' What emotion does this rule address?",
    options: [
      "Fear",
      "Boredom",
      "Greed — holding for a bigger gain until the trade reverses",
      "Confusion",
    ],
    answer: 2,
    explanation: "The market moves in your favor, but you hold for more. Then it reverses and you hesitate. The greed factor turns a winning trade into a loss.",
  },
  {
    id: 5,
    bookId: 3,
    chapter: null,
    topic: "Rule #5",
    question: "Rule #5 states: 'Your biggest loser can't exceed your biggest winner.' Why?",
    options: [
      "Because your broker will close your account",
      "Because if your biggest loss exceeds your biggest win, netting the two gives you a loss for the day",
      "Because it's illegal to lose more than you win",
      "Because you'll get a margin call",
    ],
    answer: 1,
    explanation: "If your best winner is 5 points but you let a loser run to 6 points, netting those two trades puts you in the red. Cap your losses below your best win.",
  },
  {
    id: 6,
    bookId: 3,
    chapter: null,
    topic: "Rule #7",
    question: "Rule #7: 'Be yourself. Don't try to be someone else.' What does the author mean?",
    options: [
      "Don't use a fake name when trading",
      "Trade within your comfort zone — if you can't handle large positions emotionally, don't trade them",
      "Never copy anyone's strategy",
      "Only trade one market",
    ],
    answer: 1,
    explanation: "The author knew his comfort zone was 10-20 lots. Trading 50 lots like his colleagues caused him to 'butcher' trades. Know your limits.",
  },
  {
    id: 7,
    bookId: 3,
    chapter: null,
    topic: "Rule #9",
    question: "Rule #9: 'Earn the right to trade bigger.' How does the author say you earn it?",
    options: [
      "By depositing more money",
      "By showing 10 consecutive profitable days trading one lot before moving to two lots",
      "By passing a certification exam",
      "By trading for at least one year",
    ],
    answer: 1,
    explanation: "Prove profitability at one lot for 10 straight days. Only then have you earned the right to trade two lots. Size up gradually through consistent results.",
  },
  {
    id: 8,
    bookId: 3,
    chapter: null,
    topic: "Rule #10 & #11",
    question: "Rules #10 and #11 both deal with losing trades. What do they say?",
    options: [
      "Hold losers longer to give them time to recover",
      "Get out of losers quickly — the first loss is the best loss",
      "Average down on losing positions",
      "Only exit losers at the end of the day",
    ],
    answer: 1,
    explanation: "#10: Get out of your losers. #11: The first loss is the best loss. Once you know a trade is no good, exit immediately — it's not coming back.",
  },
  {
    id: 9,
    bookId: 3,
    chapter: null,
    topic: "Rule #12",
    question: "Rule #12: 'Don't hope and pray. If you do, you will lose.' What does this mean?",
    options: [
      "Religious traders perform worse",
      "If you're praying for a trade to work, that's your gut telling you it's already bad — just get out",
      "You should never be optimistic about trades",
      "Prayer is only useful after market hours",
    ],
    answer: 1,
    explanation: "The author admits praying to the 'Bond god' as a new trader. He learned that if you're praying, the trade is already lost. Exit instead of hoping.",
  },
  {
    id: 10,
    bookId: 3,
    chapter: null,
    topic: "Rule #13",
    question: "Rule #13: 'Don't worry about news. It's history.' What does the author mean?",
    options: [
      "News never affects the market",
      "By the time news reaches CNBC, professional traders have already acted on it — you're too late",
      "You should never read the news",
      "Only historical news from 100+ years ago matters",
    ],
    answer: 1,
    explanation: "The story has been dissected by professionals long before the TV anchors report it. Trading off CNBC headlines means you're always late to the move.",
  },
  {
    id: 11,
    bookId: 3,
    chapter: null,
    topic: "Rule #14",
    question: "Rule #14: 'Don't speculate. If you do, you will lose.' What should you do instead?",
    options: [
      "Only invest long-term",
      "Trade short-term with small winners and smaller losers — be a trader, not a speculator",
      "Only trade once per week",
      "Speculate but with a larger account",
    ],
    answer: 1,
    explanation: "The author has never met a successful speculator. Short-term scalping with small wins/losses gives a much higher probability of a profitable day or week.",
  },
  {
    id: 12,
    bookId: 3,
    chapter: null,
    topic: "Rule #15",
    question: "Rule #15 says 'Love to lose money.' What does the author actually mean?",
    options: [
      "Enjoy blowing up your account",
      "Accept that losing trades are part of the game — love exiting losers quickly because it saves your capital",
      "You should intentionally lose money to learn",
      "Losing money builds character",
    ],
    answer: 1,
    explanation: "Love getting out of losers fast. A typical day is 33% losers, 33% scratches, 33% winners. Exit losers quickly and you still go home a winner.",
  },
  {
    id: 13,
    bookId: 3,
    chapter: null,
    topic: "Rule #18 & #19",
    question: "Rules #18 and #19 say: 'Make a little bit every day' and 'Hit singles, not home runs.' What's the philosophy?",
    options: [
      "Only trade one contract and one market",
      "Consistent small daily gains compound into large yearly profits — don't chase big wins",
      "Never take a trade with more than 1 point potential",
      "Only trade in the first hour of the day",
    ],
    answer: 1,
    explanation: "The author's mentor told him 10 bond tics/day ($312.50) = $72,500/year. Small consistent gains beat swinging for the fences every time.",
  },
  {
    id: 14,
    bookId: 3,
    chapter: null,
    topic: "Rule #21",
    question: "Rule #21: 'Learn to sweat out (scale out) your winners.' What does this mean?",
    options: [
      "Hold every position until it loses money",
      "Exit half your position at the first profit target and let the rest ride with a stop at breakeven",
      "Never take partial profits",
      "Double your position when winning",
    ],
    answer: 1,
    explanation: "Scale out: exit half at your first target, then you're 'playing with house money.' Move your stop to breakeven — you can't lose on the remaining position.",
  },
  {
    id: 15,
    bookId: 3,
    chapter: null,
    topic: "Rule #25",
    question: "Rule #25: 'It's the market itself that wields the ultimate scale of justice.' What does this mean?",
    options: [
      "The SEC monitors all trades for fairness",
      "The market doesn't care about you — it rewards discipline and punishes those who break the rules",
      "Markets are always fair and never manipulated",
      "Justice means every trader makes the same amount",
    ],
    answer: 1,
    explanation: "The market plays no favorites and doesn't discriminate. Follow the 25 rules and you'll be rewarded. Break them and the market will punish you mercilessly.",
  },
];
