/**
 * Book 2 — Day Trading 101
 *
 * 30 questions across 3 chapter groups:
 *   Chapter group 1: Markets, Instruments & Getting Started (Ch 1, 3-4)
 *   Chapter group 2: Trading Plans, Risk & Capital Preservation (Ch 2, 5)
 *   Chapter group 3: Trade Setups, Margin & Market Analysis (Ch 6-7)
 */

import type { QuizQuestion } from "./types";

export const BOOK_02_META = {
  id: 2,
  title: "Day Trading 101",
  shortTitle: "Day Trading 101",
};

export const BOOK_02_QUESTIONS: QuizQuestion[] = [
  // ── Chapter Group 1: Markets, Instruments & Getting Started ────────

  {
    id: 1,
    bookId: 2,
    chapter: 1,
    topic: "Markets & Instruments",
    question: "According to the book, what two things differentiate a trader from an investor?",
    options: [
      "The type of broker and the number of screens",
      "Leverage and time of trade",
      "Education level and account balance",
      "Whether they use technical or fundamental analysis",
    ],
    answer: 1,
    explanation: "The book states traders use leverage (margin) and trade on shorter time frames, while investors use cash accounts and hold for the long term.",
  },
  {
    id: 2,
    bookId: 2,
    chapter: 1,
    topic: "Markets & Instruments",
    question: "What margin ratio can futures contracts offer, according to the book?",
    options: [
      "2:1",
      "10:1",
      "50:1",
      "500:1",
    ],
    answer: 2,
    explanation: "The book states futures offer margin up to 50:1 — for every $1 of collateral, you can control $50 worth of contracts.",
  },
  {
    id: 3,
    bookId: 2,
    chapter: 1,
    topic: "Markets & Instruments",
    question: "What are the easiest futures markets for beginners to start with, according to the book?",
    options: [
      "Agricultural futures like corn and soybeans",
      "Gold, oil, and the S&P 500",
      "Treasury bond futures",
      "Foreign currency futures only",
    ],
    answer: 1,
    explanation: "The book recommends gold, oil, and S&P 500 futures because they connect to ETFs and equities, offering on-the-job training.",
  },
  {
    id: 4,
    bookId: 2,
    chapter: 1,
    topic: "Markets & Instruments",
    question: "What is a 'pip' in Forex trading?",
    options: [
      "A type of currency pair",
      "A basis point — the smallest unit of price movement in FX, used to measure commissions",
      "A stop-loss order in the FX market",
      "The spread between bid and ask",
    ],
    answer: 1,
    explanation: "A pip (basis point) is the smallest price increment in FX. Commissions are measured in pips — e.g., 1 pip on a 10,000 EUR/USD trade = 1 EUR.",
  },
  {
    id: 5,
    bookId: 2,
    chapter: 1,
    topic: "Markets & Instruments",
    question: "Why does the book say cryptocurrencies are best traded using technical analysis rather than fundamentals?",
    options: [
      "Because crypto markets are closed on weekends",
      "Because there are few tangible relationships tethered to their prices unlike bonds or commodities",
      "Because fundamental data for crypto is freely available",
      "Because crypto never moves based on news",
    ],
    answer: 1,
    explanation: "Unlike bonds, commodities, and stocks, crypto has few tangible fundamentals tied to price — making chart-based technical analysis the primary tool.",
  },
  {
    id: 6,
    bookId: 2,
    chapter: 1,
    topic: "Markets & Instruments",
    question: "What is 'quantitative easing' (QE) as described in the book?",
    options: [
      "A trading strategy that uses algorithms",
      "When central banks create new money and flood the financial system to stimulate the economy",
      "A method of calculating position sizes",
      "When brokers ease margin requirements",
    ],
    answer: 1,
    explanation: "QE is when central banks lower rates to near zero and inject newly created money into the financial system, which the book ties to the post-pandemic trading boom.",
  },
  {
    id: 7,
    bookId: 2,
    chapter: 4,
    topic: "Markets & Instruments",
    question: "What is an ETF, according to the book?",
    options: [
      "An electronic trading fee",
      "A basket of individual stocks or products that trades like a single stock and offers built-in diversification",
      "A type of futures contract",
      "An exchange-only trading format",
    ],
    answer: 1,
    explanation: "ETFs are baskets of stocks/assets that trade on exchanges like individual stocks, giving you sector exposure with diversification built in.",
  },
  {
    id: 8,
    bookId: 2,
    chapter: 4,
    topic: "Markets & Instruments",
    question: "What does the book say about the relationship between interest rates and stock prices?",
    options: [
      "They always move in the same direction",
      "Lower interest rates usually lead to higher stock prices; higher rates lead to lower prices",
      "Interest rates have no effect on stocks",
      "Higher rates always cause stocks to crash immediately",
    ],
    answer: 1,
    explanation: "Central banks raise/lower rates based on inflation and economic activity. Lower rates increase liquidity and are fuel for market rallies.",
  },
  {
    id: 9,
    bookId: 2,
    chapter: 4,
    topic: "Markets & Instruments",
    question: "What does 'market cap' mean?",
    options: [
      "The maximum price a stock can reach",
      "Share price multiplied by the number of outstanding shares",
      "The daily trading volume limit",
      "The cap on how much you can invest",
    ],
    answer: 1,
    explanation: "Market capitalization = share price x outstanding shares. It represents the market's total valuation of the company.",
  },
  {
    id: 10,
    bookId: 2,
    chapter: 4,
    topic: "Markets & Instruments",
    question: "What does it mean when a stock 'beats' earnings estimates?",
    options: [
      "The stock price went up that day",
      "The company reported better-than-expected profits, often causing the stock to rise",
      "The company paid a higher dividend than usual",
      "The company beat its competitors in revenue",
    ],
    answer: 1,
    explanation: "An earnings 'beat' means actual results exceeded analyst estimates. The good news often spreads to other stocks in the same sector.",
  },

  // ── Chapter Group 2: Trading Plans, Risk & Capital Preservation ────

  {
    id: 11,
    bookId: 2,
    chapter: 2,
    topic: "Trading Plans",
    question: "The book describes 'risk-on' and 'risk-off' days. What is a risk-off day?",
    options: [
      "A day when the markets are closed",
      "A day when markets are down, everything is in the red, and investors are fleeing to safe assets",
      "A day when you take no risks at all",
      "A day when only low-risk stocks trade",
    ],
    answer: 1,
    explanation: "Risk-off = markets falling, fear rising, traders moving to safe havens (bonds, gold, JPY, CHF). Risk-on = markets up, confidence high.",
  },
  {
    id: 12,
    bookId: 2,
    chapter: 2,
    topic: "Trading Plans",
    question: "What is a 'hedge' in trading?",
    options: [
      "A risky bet that doubles your position",
      "A trade you make to offset possible loss from another trade — like insurance",
      "A type of stop-loss order",
      "Buying more of a stock you already own",
    ],
    answer: 1,
    explanation: "The book describes hedging as trading insurance — e.g., buying a Treasury ETF to cushion a stock trade if the economy slows.",
  },
  {
    id: 13,
    bookId: 2,
    chapter: 2,
    topic: "Trading Plans",
    question: "What does the book recommend doing on a major news day (e.g., Fed announcement)?",
    options: [
      "Trade aggressively to capture the big move",
      "Double your position size for the opportunity",
      "Avoid trading or have no positions ahead of the announcement, since outcomes can't be predicted",
      "Only trade penny stocks on news days",
    ],
    answer: 2,
    explanation: "The book advises capital preservation first — avoid positions ahead of major announcements since the market reaction is unpredictable.",
  },
  {
    id: 14,
    bookId: 2,
    chapter: 2,
    topic: "Trading Plans",
    question: "What are 'consensus estimates' in the context of economic reports?",
    options: [
      "The actual results of an economic report",
      "Market predictions about what an economic report will say, used as reaction benchmarks",
      "The average stock price prediction from analysts",
      "The consensus opinion of CNBC commentators",
    ],
    answer: 1,
    explanation: "Consensus estimates are the market's expected numbers. If the actual report differs from estimates, the market moves accordingly.",
  },
  {
    id: 15,
    bookId: 2,
    chapter: 5,
    topic: "Risk Management",
    question: "What does the book say should be your PRIMARY objective in day trading?",
    options: [
      "Maximizing profit on every trade",
      "Capital preservation — keeping your losses as small as possible",
      "Beating the S&P 500 every month",
      "Making at least 10 trades per day",
    ],
    answer: 1,
    explanation: "The book's #1 rule: capital preservation first, capital gains second. If your primary goal is managing risk, you'll stay in the game longer.",
  },
  {
    id: 16,
    bookId: 2,
    chapter: 5,
    topic: "Risk Management",
    question: "What is the '2% rule' in risk management?",
    options: [
      "You must make 2% profit on every trade",
      "Close trades with no more than 2% of your total account balance lost",
      "Only trade 2% of the time",
      "Keep 2% of your account in cash",
    ],
    answer: 1,
    explanation: "The 2% rule limits any single trade's loss to 2% of your account. With this rule, you could theoretically have 50 consecutive losers before going to zero.",
  },
  {
    id: 17,
    bookId: 2,
    chapter: 5,
    topic: "Risk Management",
    question: "According to the book, what is a 'moving stop'?",
    options: [
      "A stop-loss that moves to a different broker",
      "An automatic sell order that moves up as the stock price rises, locking in profits",
      "A stop that only works during market hours",
      "A stop-loss order that expires after 30 minutes",
    ],
    answer: 1,
    explanation: "Moving stops trail behind the rising price — if a stock moves from $15 to $18.75, your stop moves up from $12.50 to $16.25, locking in gains.",
  },
  {
    id: 18,
    bookId: 2,
    chapter: 5,
    topic: "Risk Management",
    question: "The book says to view your trading account as a what?",
    options: [
      "A gambling fund",
      "A cash account — your primary objective is capital preservation",
      "An emergency savings account",
      "A retirement fund",
    ],
    answer: 1,
    explanation: "Think of it as cash. Be in cash until a trade presents itself, then return to cash. Cash = safety. Each trade is a supplement to your risk-free interest.",
  },
  {
    id: 19,
    bookId: 2,
    chapter: 5,
    topic: "Risk Management",
    question: "What does the book mean by 'offensive' vs 'defensive' risk in your cash account?",
    options: [
      "Offensive = fighting with your broker; Defensive = protecting your password",
      "Offensive = entering/exiting trades to grow net worth; Defensive = preserving your paycheck and business cash",
      "Offensive = day trading; Defensive = investing",
      "Offensive = using margin; Defensive = using cash only",
    ],
    answer: 1,
    explanation: "Defensive trading preserves capital to survive. Offensive trading actively seeks gains. The book says switch between them as conditions change throughout the day.",
  },
  {
    id: 20,
    bookId: 2,
    chapter: 5,
    topic: "Risk Management",
    question: "What does the book say you should view every loss as?",
    options: [
      "A failure that means you should quit",
      "A withdrawal from your trading account — and you must earn it back plus expenses",
      "Something to ignore and move on from",
      "Proof that the market is rigged",
    ],
    answer: 1,
    explanation: "A $500 loss + $500 in monthly expenses = a $1,000 withdrawal. You need $1,000 in profits just to get back to your starting balance.",
  },

  // ── Chapter Group 3: Trade Setups, Margin & Market Analysis ────────

  {
    id: 21,
    bookId: 2,
    chapter: 6,
    topic: "Trade Setups & Margin",
    question: "According to the book, what is the correct order for finding a trade setup?",
    options: [
      "Pick a stock, then check the news",
      "Start with the big picture (news), confirm with price charts, then choose the market and find the specific trade",
      "Follow social media tips, then buy immediately",
      "Use only one indicator and trade when it signals",
    ],
    answer: 1,
    explanation: "The book says: review news first → confirm with charts → decide what market → drill into specific trades. Top-down analysis.",
  },
  {
    id: 22,
    bookId: 2,
    chapter: 6,
    topic: "Trade Setups & Margin",
    question: "How does margin work, according to the book?",
    options: [
      "It's free money from your broker",
      "It's a loan — you put up cash/securities as collateral and the broker lends you more buying power",
      "It's the profit margin on your trades",
      "It's the gap between bid and ask price",
    ],
    answer: 1,
    explanation: "Margin is a loan from your broker using your account as collateral. It amplifies both gains AND losses proportionally.",
  },
  {
    id: 23,
    bookId: 2,
    chapter: 6,
    topic: "Trade Setups & Margin",
    question: "The book gives a margin math example: you invest $10,000 cash + $5,000 margin to buy $15,000 of an ETF that goes up 10%. What is your actual percentage gain?",
    options: [
      "10%",
      "15%",
      "5%",
      "50%",
    ],
    answer: 1,
    explanation: "$15,000 × 10% = $1,500 gain. But you only invested $10,000 cash, so $1,500 / $10,000 = 15% return. Margin amplifies your percentage returns.",
  },
  {
    id: 24,
    bookId: 2,
    chapter: 6,
    topic: "Trade Setups & Margin",
    question: "What happens when you receive a margin call?",
    options: [
      "Your broker gives you a bonus",
      "You must add cash to bring your account back to the minimum, or the broker may close your positions",
      "You get a phone call recommending trades",
      "Your account is upgraded to premium",
    ],
    answer: 1,
    explanation: "A margin call means your collateral has fallen below the minimum. You must deposit more cash or the broker will liquidate your positions — often at the worst time.",
  },
  {
    id: 25,
    bookId: 2,
    chapter: 6,
    topic: "Trade Setups & Margin",
    question: "What is the 'pyramid method' for building positions?",
    options: [
      "A pyramid scheme in trading",
      "Building positions in three separate groups and closing them one at a time to average prices and lock in gains",
      "Always adding to losing positions",
      "Trading three different stocks at once",
    ],
    answer: 1,
    explanation: "The pyramid method enters in stages and exits in stages, averaging your cost and preventing the risk of establishing a large position at one unfavorable price.",
  },
  {
    id: 26,
    bookId: 2,
    chapter: 3,
    topic: "Costs & Business of Trading",
    question: "How are day trading profits taxed, according to the book?",
    options: [
      "They are tax-free",
      "As short-term capital gains at your regular income tax rate",
      "At a flat 15% rate",
      "Only if you withdraw from your trading account",
    ],
    answer: 1,
    explanation: "Day trading profits are short-term capital gains (held less than 1 year) and taxed at your regular income tax rate — not the lower long-term rate.",
  },
  {
    id: 27,
    bookId: 2,
    chapter: 3,
    topic: "Costs & Business of Trading",
    question: "What does the book say about taking a 'salary' from your trading account?",
    options: [
      "Never withdraw money from your trading account",
      "Take regular withdrawals as a paycheck — it makes trading a real job and prevents greed from growing your positions too large",
      "Only withdraw once per year",
      "Reinvest everything until you have $1 million",
    ],
    answer: 1,
    explanation: "The book says taking a paycheck ensures you enjoy the profits and prevents positions from growing dangerously large. It's a business — pay yourself.",
  },
  {
    id: 28,
    bookId: 2,
    chapter: 7,
    topic: "Market Analysis",
    question: "What is the difference between fundamental analysis and technical analysis?",
    options: [
      "Fundamental uses charts; technical uses news",
      "Fundamental examines financial statements, economics, and company data; technical uses price charts and past patterns",
      "There is no difference — they're the same thing",
      "Fundamental is for stocks only; technical is for Forex only",
    ],
    answer: 1,
    explanation: "Fundamentals tell the story of what's happening; technicals confirm whether the market agrees. The book says use both together.",
  },
  {
    id: 29,
    bookId: 2,
    chapter: 7,
    topic: "Market Analysis",
    question: "What is the P/E ratio?",
    options: [
      "Profit / Expenses",
      "Price of the stock divided by its earnings per share — tells you how expensive the stock is relative to its earnings",
      "The percentage of equity in your account",
      "The performance evaluation score from your broker",
    ],
    answer: 1,
    explanation: "P/E = Price / Earnings Per Share. A high P/E means the stock is expensive relative to its earnings. Compare P/E ratios within the same sector.",
  },
  {
    id: 30,
    bookId: 2,
    chapter: 7,
    topic: "Market Analysis",
    question: "What does the CNN Fear and Greed Index measure?",
    options: [
      "How many traders are online",
      "Market sentiment — readings below 25 indicate extreme fear, above 70 indicate extreme greed",
      "The number of stocks going up vs down",
      "Your personal trading performance",
    ],
    answer: 1,
    explanation: "The Fear and Greed Index puts a number on market sentiment. Extreme readings often precede major trend changes — greed at tops, fear at bottoms.",
  },
];
