/**
 * Book 4 — The Ultimate Trading Risk Management Guide (Steve Burns & Holly Burns)
 *
 * 20 questions across 2 chapter groups:
 *   Group 1: Risk Types, R/R Ratios, Stop Losses, Position Sizing (Ch 1-7)
 *   Group 2: Diversification, Cash, Moving Averages, Options, Causes of Losses (Ch 8-14)
 */

import type { QuizQuestion } from "./types";

export const BOOK_04_META = {
  id: 4,
  title: "The Ultimate Trading Risk Management Guide",
  shortTitle: "Risk Management Guide",
};

export const BOOK_04_QUESTIONS: QuizQuestion[] = [
  // ── Group 1: Risk Types, R/R Ratios, Stop Losses, Position Sizing ──

  {
    id: 1,
    bookId: 4,
    chapter: 1,
    topic: "Trading Risks",
    question: "According to the book, what is the biggest mistake you can make in risk management?",
    options: [
      "Using too many indicators",
      "Being on the wrong side of a trend with a large position and stubbornly letting it run against you",
      "Trading during pre-market hours",
      "Using a discount broker",
    ],
    answer: 1,
    explanation: "The book says the biggest mistake is being wrong with a large position and refusing to exit. If you don't know what to do, go to cash.",
  },
  {
    id: 2,
    bookId: 4,
    chapter: 1,
    topic: "Trading Risks",
    question: "What is 'liquidity risk' in trading?",
    options: [
      "The risk of your broker going bankrupt",
      "When there aren't enough buyers/sellers, causing wide spreads and slippage on entry and exit",
      "The risk of trading during lunch hours",
      "When your internet connection is too slow",
    ],
    answer: 1,
    explanation: "Low liquidity means wide bid/ask spreads. You can lose 10%+ just on the round-trip of buying at the ask and selling at the bid on a penny stock.",
  },
  {
    id: 3,
    bookId: 4,
    chapter: 1,
    topic: "Trading Risks",
    question: "What is 'overnight risk'?",
    options: [
      "The risk of falling asleep while trading",
      "When something unexpected happens while the market is closed, causing a gap that bypasses your stop loss",
      "The risk of trading after 8 PM",
      "When your broker charges overnight fees",
    ],
    answer: 1,
    explanation: "Overnight risk = gaps. The market closes, bad news hits, and your position opens the next day far below your stop. Day traders avoid this by closing positions daily.",
  },
  {
    id: 4,
    bookId: 4,
    chapter: 2,
    topic: "Risk/Reward Ratios",
    question: "With a 3:1 risk/reward ratio, what win rate do you need just to break even?",
    options: [
      "50%",
      "35%",
      "25%",
      "75%",
    ],
    answer: 2,
    explanation: "At 3:1 R/R, you only need to win 25% of the time to break even. The bigger your wins relative to losses, the lower your required win rate.",
  },
  {
    id: 5,
    bookId: 4,
    chapter: 2,
    topic: "Risk/Reward Ratios",
    question: "The book shows that even with an 80% win rate, you can still lose money. How?",
    options: [
      "If commissions are too high",
      "If your few losses are much larger than your many small wins, the math works against you",
      "If you trade too infrequently",
      "If you only trade one stock",
    ],
    answer: 1,
    explanation: "The book's example: 8 wins of $100-$200 each but 2 losses of $500-$1000 = net loss of $500 despite winning 80% of the time. Loss SIZE matters more than win rate.",
  },
  {
    id: 6,
    bookId: 4,
    chapter: 3,
    topic: "Stop Losses",
    question: "According to the book, what is the root cause of most large losses?",
    options: [
      "Bad luck and market manipulation",
      "Emotion and ego — refusing to admit you're wrong and exit",
      "Using the wrong broker",
      "Trading too many different stocks",
    ],
    answer: 1,
    explanation: "The book lists: too stubborn to exit, too much ego to take a loss, too much hope for a reversal. The root is always emotion overriding the plan.",
  },
  {
    id: 7,
    bookId: 4,
    chapter: 3,
    topic: "Stop Losses",
    question: "What is the difference between a stop loss and a trailing stop?",
    options: [
      "They are the same thing",
      "A stop loss exits a losing trade; a trailing stop follows a winning trade upward to lock in profits",
      "A stop loss is automatic; a trailing stop is manual",
      "A trailing stop is only for options",
    ],
    answer: 1,
    explanation: "Stop loss = your defense against losses (fixed exit point). Trailing stop = your offense for winners (moves up with price to lock in gains as the trend continues).",
  },
  {
    id: 8,
    bookId: 4,
    chapter: 4,
    topic: "Trailing Stops",
    question: "What can you use as technical indicators for placing trailing stops?",
    options: [
      "Only the 200-day moving average",
      "Short-term MAs, MA crossovers, ATR retracements, previous day's low, or candlestick reversals",
      "Only round numbers like $50, $100",
      "The VIX level only",
    ],
    answer: 1,
    explanation: "The book lists multiple trailing stop methods: short-term EMAs, MA crossovers, ATR, close below previous day's low, and candlestick reversal patterns.",
  },
  {
    id: 9,
    bookId: 4,
    chapter: 5,
    topic: "Position Sizing",
    question: "According to the book, what determines your position size?",
    options: [
      "How much money is in your account",
      "The placement of your stop loss and the volatility of the stock — the stop comes first, then you size accordingly",
      "Whatever your broker recommends",
      "The stock's current price",
    ],
    answer: 1,
    explanation: "Stop loss placement comes first. Then you calculate position size so that if the stop is hit, you only lose your maximum allowed percentage (e.g., 1%).",
  },
  {
    id: 10,
    bookId: 4,
    chapter: 5,
    topic: "Position Sizing",
    question: "The book recommends what position sizing for individual stocks, stock index ETFs, futures, and options respectively?",
    options: [
      "25% / 50% / 25% / 10%",
      "10% / 25% / 5% / 1% of total trading capital",
      "Equal amounts for all",
      "100% in whatever has the best signal",
    ],
    answer: 1,
    explanation: "The book's guidelines: 10% for individual stocks, 25% for index ETFs, 5% for futures contracts, 1% for options — reflecting the leverage and risk of each.",
  },

  // ── Group 2: 1% Rule, Risk of Ruin, Diversification, Cash, MAs, Options ──

  {
    id: 11,
    bookId: 4,
    chapter: 6,
    topic: "The 1% Rule",
    question: "The 1% rule says 'never risk more than 1% of total equity on any trade.' What does '1%' refer to?",
    options: [
      "Only invest 1% of your account per trade",
      "The maximum potential loss if your stop is hit — not the position size itself",
      "Your broker's commission rate",
      "The maximum daily drawdown",
    ],
    answer: 1,
    explanation: "1% is the max LOSS, not position size. You can buy $10,000 of stock with a 10% stop — the $1,000 loss = 1% of a $100,000 account. Position size and risk are different.",
  },
  {
    id: 12,
    bookId: 4,
    chapter: 6,
    topic: "The 1% Rule",
    question: "If you have 6 open positions each risking 1%, and all hit their stops on the same day, what's your total drawdown?",
    options: [
      "1%",
      "3%",
      "6%",
      "60%",
    ],
    answer: 2,
    explanation: "6 positions × 1% each = 6% portfolio heat. The book calls this manageable — it's a bad day, not a career-ending one.",
  },
  {
    id: 13,
    bookId: 4,
    chapter: 7,
    topic: "Risk of Ruin",
    question: "If you lose 50% of your trading account, what return do you need to get back to breakeven?",
    options: [
      "50%",
      "75%",
      "100%",
      "200%",
    ],
    answer: 2,
    explanation: "A 50% loss on $100,000 leaves $50,000. You need a 100% return on $50,000 to get back to $100,000. Drawdowns cut deeper than gains heal.",
  },
  {
    id: 14,
    bookId: 4,
    chapter: 7,
    topic: "Risk of Ruin",
    question: "The book shows that risking 1% per trade results in less than a 10% drawdown after 10 consecutive losses, while risking 5% per trade results in what?",
    options: [
      "A 15% drawdown",
      "A 30% drawdown",
      "A 50% drawdown",
      "A 40% drawdown",
    ],
    answer: 3,
    explanation: "1% risk = ~10% drawdown after 10 losses. 5% risk = ~40% drawdown after 10 losses. The percentage compounds because each loss is from a shrinking balance.",
  },
  {
    id: 15,
    bookId: 4,
    chapter: 8,
    topic: "Diversification",
    question: "Why does the book warn that holding 10 correlated stocks is NOT true diversification?",
    options: [
      "Because you can only watch 5 stocks at once",
      "Because in a market crash, all correlated stocks drop together — your 1% per-stock risk becomes 10% total",
      "Because your broker charges more for 10 positions",
      "Because they all have the same ticker symbol",
    ],
    answer: 1,
    explanation: "In corrections and bear markets, correlated assets move in sync. Ten tech stocks at 1% risk each = 10% drawdown if they all gap down on the same day.",
  },
  {
    id: 16,
    bookId: 4,
    chapter: 9,
    topic: "Cash is a Position",
    question: "The book says 'Cash is a position.' What does this mean?",
    options: [
      "You should always keep cash under your mattress",
      "Staying in cash when there are no good setups IS a valid trading decision — it protects capital and avoids overtrading",
      "Cash-only accounts are better than margin accounts",
      "You should only trade with physical cash, not margin",
    ],
    answer: 1,
    explanation: "Overtrading from fear, greed, or boredom is one of the biggest destroyers. The best trades come from patience — when the market doesn't favor your system, stay in cash.",
  },
  {
    id: 17,
    bookId: 4,
    chapter: 10,
    topic: "Moving Averages",
    question: "What is the difference between a Simple Moving Average (SMA) and an Exponential Moving Average (EMA)?",
    options: [
      "SMAs are for stocks, EMAs are for futures",
      "An EMA gives more weight to recent prices, making it react faster to new price action than an SMA",
      "An SMA is always faster than an EMA",
      "There is no practical difference",
    ],
    answer: 1,
    explanation: "SMAs weight all prices equally. EMAs weight recent prices more heavily, making them faster to react — useful for limiting losses in fast-moving markets.",
  },
  {
    id: 18,
    bookId: 4,
    chapter: 10,
    topic: "Moving Averages",
    question: "When multiple moving averages converge at the same price level, what does the book say this indicates?",
    options: [
      "The stock is about to be delisted",
      "The market is range-bound and not trending — MAs aren't useful until price breaks above the convergence",
      "You should immediately buy the stock",
      "The moving averages are broken",
    ],
    answer: 1,
    explanation: "When the 10, 50, and 100-day MAs converge (like the ETSY example), the chart is range-bound. Price closing above the convergence sets up a potential new trend entry.",
  },
  {
    id: 19,
    bookId: 4,
    chapter: 11,
    topic: "Never Risk Your Lifestyle",
    question: "Ed Seykota says: 'Speculate with less than 10% of your liquid net worth.' What does the book say this means practically?",
    options: [
      "Only trade 10% of the time",
      "Your trading account should be no more than 10% of your total liquid net worth, so blowing it up doesn't ruin your life",
      "Keep 10% of your trades as long-term investments",
      "Only risk 10% per trade",
    ],
    answer: 1,
    explanation: "If your liquid net worth is $100,000, your trading account should be ~$10,000. If you blow it up, you still have 90% of your net worth intact.",
  },
  {
    id: 20,
    bookId: 4,
    chapter: 13,
    topic: "Causes of Trading Losses",
    question: "The book says every trade should end in one of four ways. Which is NOT one of them?",
    options: [
      "A small win",
      "A big win",
      "A big loss",
      "A small loss",
    ],
    answer: 2,
    explanation: "The four outcomes: small win, big win, small loss, or break even. A big loss should NEVER happen — eliminating it as an outcome is the entire point of risk management.",
  },
];
